### ISSUE TITLE
Que le paso al codigo?

### ISSUE THREAD

**Issue by Mint2D** [PabloTriana/ProgramacionWeb_Equipo14#1]
Pablo probablemente borro por accidente el repositorio xD

**Comment by danielasanchez** [comment]
No se que hicieron, pero el repositorio esta publico y debe estar privado xD

**Comment by PabloTriana** [comment]
Esque me salia si estaba privado no me dejaba hacer el deploy, pero no creo
que nadie nos copie a nosotros profe😂

**Comment by Mint2D** [comment]
> Esque me salia si estaba privado no me dejaba hacer el deploy, pero no creo que nadie nos copie a nosotros profe😂

pues con la bendicion de dios esperemos que no xD.
